CREATE DATABASE IF NOT EXISTS ultron DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `user` (
	`id` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`username` VARCHAR (10) NOT NULL,
	`credit_no` VARCHAR (18) NOT NULL COMMENT '二代身份证号码',
	`phone` VARCHAR (14) NOT NULL,
	`create_user` VARCHAR(20) NOT NULL,
	`create_time` TIMESTAMP (3) NOT NULL DEFAULT CURRENT_TIMESTAMP (3)
) COMMENT '用户表';

CREATE TABLE `user_info` (
	`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	`user_id` BIGINT(20) NOT NULL,
	`province` VARCHAR(10) NOT NULL COMMENT '省份',
	`city` VARCHAR(10) NULL,
	`distrct` VARCHAR(10) NULL,
	`brithday` VARCHAR(10) NOT NULL,
	`sex` TINYINT(1) NOT NULL,
	`create_user` VARCHAR(20) NOT NULL,
	`create_time` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
)COMMENT '用户信息';