info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ultron?useSSL=false
    username: root
    password: W15bmjkpa
    driver-class-name: com.mysql.jdbc.Driver
    connectionInitSqls: set names utf8mb4;
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikaraiCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml

