server:
  port: 8765

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ultron?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: W15bmjkpa
    driver-class-name: com.mysql.jdbc.Driver
    connectionInitSqls: set names utf8mb4;
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikaraiCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  session:
    timeout: 43200
    store-type: none
    servlet:
      filter-dispatcher-types: request
      filter-order: 100

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml

jwt-token:
  service-name: ultron-boss
  service-id: 098f6bcd4621d373cade4e832627b4f6
  secret-key: Fqtt1LcUz8bkDVKH0CO+b91EvtH60E7vweYGGN4PgxE=
  expire-seconds: 7200
